IncedoSolution/MvcApp01/Controllers/AdoDemoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data.SqlClient;

namespace MvcApp01.Controllers
{
    public class AdoDemoController : Controller
    {
        string cs = string.Empty;
        SqlConnection cn = null;
        public SqlConnection ConnectToSql()
        {
            string cs = "server=G1-443HZH3-L\\SQLEXPRESS; integrated security=true; database=IncedoEmployeeDB";
            cn = new SqlConnection(cs);
            cn.Open();
            return cn;
        }
        [HttpGet]
        public IActionResult Index()
        { 
            return View();
        }
        [HttpPost]
        public IActionResult Index(int id, string ename, string job, int salary, string b1)
        {
            string query = string.Empty;
            switch (b1)
            {
                case "Retrieve":
                    query = "Select * from tblEmployees where id=@id";
                    SqlCommand cmd = new SqlCommand(query, ConnectToSql());
                    cmd.Parameters.AddWithValue("@id", id);
                    SqlDataReader dr = cmd.ExecuteReader();
                    if(dr.Read())
                    {
                        ViewBag.id = $"Employee Id : {dr[0].ToString()}";
                        ViewBag.ename = $"Employee Name : {dr[1].ToString()}";
                        ViewBag.job = $"Employee Job : {dr[2].ToString()}";
                        ViewBag.salary = $"Employee Salary : {dr[3].ToString()}";
                    }
                    else
                    {
                        ViewBag.msg = $"{id} not exist...";
                    }
                    break;
                case "Create":
                    query = "Insert into tblEmployees values (@id,@ename,@job,@salary)";
                    cmd = new SqlCommand(query, ConnectToSql());
                    cmd.Parameters.AddWithValue("@id", id);
                    cmd.Parameters.AddWithValue("@ename", ename);
                    cmd.Parameters.AddWithValue("@job", job);
                    cmd.Parameters.AddWithValue("@salary", salary);
                    int count = cmd.ExecuteNonQuery();
                    ViewBag.msg = $"{count} rows added successfully...";
                    break;
                case "Update":
                    query = "Update tblEmployees set ename=@ename,job=@job,salary=@salary where id=@id";
                    cmd = new SqlCommand(query, ConnectToSql());
                    cmd.Parameters.AddWithValue("@id", id);
                    cmd.Parameters.AddWithValue("@ename", ename);
                    cmd.Parameters.AddWithValue("@job", job);
                    cmd.Parameters.AddWithValue("@salary", salary);
                    count = cmd.ExecuteNonQuery();
                    ViewBag.msg = $"{count} rows updated successfully...";
                    break;
                case "Delete":
                    query = "Delete tblEmployees where id=@id";
                    cmd = new SqlCommand(query, ConnectToSql());
                    cmd.Parameters.AddWithValue("@id", id);
                    count = cmd.ExecuteNonQuery();
                    ViewBag.msg = $"{count} rows deleted successfully...";
                    break;
                default:
                    break;
            }
            return View();
        }
    }
}

IncedoSolution/MvcApp01/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MvcApp01.Models;

namespace MvcApp01.Controllers
{
    public class CustomersController : Controller
    {
        static CustomerBO context = new CustomerBO();
        public IActionResult Index()
        {
            List<CustomerModel> Customers = context.Customers;
            return View(Customers);
        }
        public IActionResult Details(int id)
        {
            CustomerModel Customers = context.Customers.Single(x=>x.Id==id);
            return View(Customers);
        }
        [HttpGet]
        public IActionResult Create()
        { 
            return View();
        }
        [HttpPost]
        public IActionResult Create(CustomerModel C1)
        {
            context.Customers.Add(C1);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            CustomerModel Customers = context.Customers.Single(x => x.Id == id);
            return View(Customers);
        }
        [HttpPost]
        public IActionResult Edit(CustomerModel C1)
        {
            int index = context.Customers.FindIndex(x => x.Id == C1.Id);
            context.Customers[index] = C1;
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            CustomerModel Customers = context.Customers.Single(x => x.Id == id);
            return View(Customers);
        }
        [HttpPost]
        public IActionResult Delete(CustomerModel C1)
        {
            int index = context.Customers.FindIndex(x => x.Id == C1.Id);
            context.Customers.RemoveAt(index);
            return RedirectToAction("Index");
        }
    }
}

IncedoSolution/MvcApp01/Controllers/RazorDemoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcApp01.Controllers
{
    public class RazorDemoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Example01()
        {
            return View();
        }
        public IActionResult Example02()
        {
            return View();
        }
        public IActionResult Example03()
        {
            return View();
        }
        public IActionResult Example04()
        {
            return View();
        }
        public IActionResult Example05()
        {
            return View();
        }
    }
}

IncedoSolution/MvcApp01/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MvcApp01.Models;

namespace MvcApp01.Controllers
{
    public class StudentsController : Controller
    {
        StudentBO context = new StudentBO();
        public IActionResult Index()
        {
            List<StudentModel> students = context.GetAllStudents();
            ViewBag.students = students;
            return View();
        }
    }
}

IncedoSolution/MvcApp01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcApp01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Harshit Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RazorDemo" asp-action="Index">Razor Demo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PassingDataDemo" asp-action="Index">Passing Data Demo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PostbackDemo" asp-action="Index">Postback Demo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HtmlHelpersDemo" asp-action="Index">Html Helpers Demo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdoDemo" asp-action="Index">ADO.Net Demo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcApp01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>